name: SecretInjection
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/ci app_secret

      - name: Injecting Secret using Vault Action
        run: |
          echo APP Secret: ${{ env.APP_SECRET }}  | sed 's/./& /g'

      - name: Injecting Secret using Vault CLI
        run: |
          VAULT_TOKEN=${{secrets.VAULT_TOKEN}} vault kv get -format=json secret/ci | jq -r ".data.data"

      - name: Injecting Secret using REST API
        run: |
          curl -H "X-Vault-Token: ${{secrets.VAULT_TOKEN}}" -X GET http://127.0.0.1:8200/v1/secret/data/ci | jq

      - name: Retrieving secret that is restricted
        run: |
          curl -H "X-Vault-Token: ${{secrets.VAULT_TOKEN}}" -X GET http://127.0.0.1:8200/v1/secret/data/restricted
